### ISSUE TITLE
Netlify deployment failed

### ISSUE THREAD

**Issue by Rudra-Sankha-Sinhamahapatra** [jaimin1503/zidio-resume-builder#15]
![image](https://github.com/jaimin1503/zidio-resume-builder/assets/101992909/5636e028-3a60-4993-b7e9-e21274502046)
why the netlify deployment failed

**Comment by jaimin1503** [comment]
I have deployed on Vercel

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
ok thanks
