### ISSUE TITLE
User not able to signup

### ISSUE THREAD

**Issue by Rudra-Sankha-Sinhamahapatra** [jaimin1503/zidio-resume-builder#17]
![image](https://github.com/jaimin1503/zidio-resume-builder/assets/101992909/f657af02-b48c-4af3-82b7-9c4f8311f436)

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
I was trying on your vercel deployed app there signup isnt working ,but in my localhost everythig is working ...Kindly ensure your mongo db database is always active and ensure theres no cors error

**Comment by jaimin1503** [comment]
Its because I haven't deployed the backend yet

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
import express from "express";
import cookieParser from "cookie-parser";
import connect from "./utils/db.js";
import dotenv from "dotenv";
dotenv.config();
import cors from "cors";
import userRoutes from "./routes/userRoutes.js";
import resumeRoutes from "./routes/resumeRoutes.js";

connect();
const app = express();
app.use(express.json());
app.use(cookieParser());
app.use(
  cors({
    origin: ["http://localhost:5173"],
    methods: ["GET", "POST", "PUT", "DELETE"],
    credentials: true,
  })
);

app.use("/user", userRoutes);
app.use("/resume", resumeRoutes);

const port = process.env.PORT || 5555;
app.listen(port, () => {
  console.log(`app is listening on port ${port}`);
});

see its your index.js here you have written the origin as the localhost url kindly remove it otherwise in the production mode it cant access the localhost .. just remove it after deploying 
because both localhost and production app both need to access the frontend

**Comment by jaimin1503** [comment]
Yeah i know
