### ISSUE TITLE
User is not able to signup

### ISSUE THREAD

**Issue by Rudra-Sankha-Sinhamahapatra** [jaimin1503/zidio-resume-builder#24]
I dont know but you made some mistake i think...
one advice please dont upload the dotenv  file in github 
Someone might delete your db from your mongodb url
Add the env variables on vercel explicitly and delete the env from github
Check why the signup endpoint is not working

**Comment by jaimin1503** [comment]
signup route is not working cause you added code validation check for it cause in error it shows "incorrect input"

**Comment by jaimin1503** [comment]
Zod* validation

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
but when i added then it was working fine i tested it before ...Zod validation is not the reason..it was working fine.After that due to some error this is happening

**Comment by jaimin1503** [comment]
Solved ,
it was a mongoDB duplicate key issue.

thanks for noticing.

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
thanks looking forward to contribute more
